baseurl = "https://voteeasy.aiki-it.de"
DefaultContentLanguage = "en" # change to e.g. "de" to see translations
title = "VoteEasy"
# Using theme as git submodule
# theme = "beautifulhugo"
# Or when using theme as hugo module
theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
[Services.Disqus]
# Shortname = "XXX"
[Services.googleAnalytics]
# id = "XXX"

[Params]
# Avoid loading stuff remotely
selfHosted = true
homeTitle = "VoteEasy" # Set a different text for the header on the home page
subtitle = "Dein einfaches Abstimmungswerkzeug"
mainSections = ["post", "posts"]
logo = "img/avatar-icon.png" # Expecting square dimensions
favicon = "img/favicon.ico"
dateFormat = "2023-10-15"
rss = true
comments = true
readingTime = true
wordCount = true
useHLJS = true
socialShare = true # prevent share stuff on each page
delayDisqus = true
showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."
commit = "https://github.com/voteeasy/webpage/tree/"
# Copyright since in footer
since = 2019
# show last modified
showPageDates = true

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
# Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
name = "Aiki IT"
website = "https://voteeasy.aiki-it.de"
# Test for https://github.com/halogenica/beautifulhugo/issues/548
# email = &#102;&#111;&#111;&#64;&#98;&#97;&#114;&#46;&#99;&#111;&#109;
email = "voteeasy@aiki-it.de"
#  facebook = "username"
github = "voteeasy"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
#  500px = "username"
#  codepen = "username"
#  mastodon = "url"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"
#  medium = "username"
#  discord = "invite code (https://discord.gg/XXXXXXX)"
#  strava = "userid"
#  lastfm = "username"
#  bluesky = "username"

[[menu.main]]
name = "Download"
url = "page/download/"
weight = 1

[[menu.main]]
identifier = "demo"
name = "Demo"
url = "page/demo/"
weight = 2

[[menu.main]]
parent = "demo"
name = "Übersicht"
url = "page/demo"
weight = 1

[[menu.main]]
parent = "demo"
name = "Registrierung"
url = "page/demo/registerlogin"
weight = 2

[[menu.main]]
parent = "demo"
name = "Abstimmungen"
url = "page/demo/abstimmungen"
weight = 3

[[menu.main]]
parent = "demo"
name = "Für Teilnehmer"
url = "page/demo/teilnehmer"
weight = 4

[[menu.main]]
parent = "demo"
name = "Als Administrator"
url = "page/demo/administrator"
weight = 5

[[menu.main]]
parent = "demo"
name = "Als VoteEasy-Superadmin"
url = "page/demo/superadmin"
weight = 6

[[menu.main]]
name = "Über uns"
url = "page/ueber-uns/"
weight = 3

#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 4

[[module.imports]]
# if imported as a hugo module
path = "github.com/halogenica/beautifulhugo"

# Show version information
enableGitInfo = true

# Allow referencing fontawesome icons or direct HTML
[markup.goldmark.renderer]
unsafe = true
